version: "3"

volumes:
  prometheus_data: {}

networks:
  monitor_network:

services:
  prometheus:
    image: prom/prometheus
    #build: "https://github.com/njmccorkle/docker-prometheus.git"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

    ports:
      - 9090:9090
    # depends_on:
      # - cadvisor
    networks:
      - monitor_network
    restart: always

    deploy:
      replicas: 1
      # resources:
        # limits:
          # cpus: "0.1"
          # memory: 50M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager



# node command
#       - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"