version: "3"

services:
  prometheus:
    #image: njmccorkle/prometheus:latest
    build: "https://github.com/njmccorkle/docker-prometheus.git"
    volumes:
      - prometheus:/prometheus
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"
    networks:
      - webnet

volumes:
  prometheus:

networks:
  webnet:
