global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

rule_files:
  - 'alert_rules.yml'
  - 'recording_rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape config for monitoring prometheus
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
    
  - job_name: 'node_linux'
    scrape_interval: 5s
    static_configs:
    - targets:
      - docker1.mccorkle.co:9100
      - docker2.mccorkle.co:9100
      - docker3.mccorkle.co:9100
      
  - job_name: 'node_freebsd'
    scrape_interval: 5s
    static_configs:
    - targets:
      - pfsense.mccorkle.co:9100
      
  - job_name: 'swarm_nodes'
    scrape_interval: 5s
    static_configs:
    - targets:
      - docker1.mccorkle.co:9323
      - docker2.mccorkle.co:9323
      - docker3.mccorkle.co:9323
