{
 "title": "Node FreeBSD",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_time_seconds{job=\"node_freebsd\"}, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(node_time_seconds{job=\"node_freebsd\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_active_bytes{instance=~\"$node:$port\"} * 100) / node_memory_size_bytes{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Waiting to: https://github.com/derekmarcotte/node_exporter/blob/3bcdd14906307da57641ea8321d47909b90d98fa/collector/memory_bsd.go",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(swap_used_bytes{instance=~\"$node:$port\"} * 100) / node_memory_swap_in_bytes_total{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "singlestat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_size_bytes{instance=~\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Total SWAP",
     "type": "singlestat",
     "description": "Total SWAP",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_swap_size_bytes{instance=~\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Total RootFS",
     "type": "singlestat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",mountpoint=\"/\"}"
      }
     ]
    },
    {
     "title": "System Load (1m avg)",
     "type": "singlestat",
     "description": "System Load (1m avg)",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "description": "System uptime - Pending https://github.com/prometheus/node_exporter/pull/550",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_time_seconds{instance=~\"$node:$port\"} - node_boot_time_seconds{instance=~\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='interrupt',instance=~\"$node:$port\"}[5m])) * 100",
       "legendFormat": "Interrupt - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node:$port\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_inactive_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "Inactive - Memory that is completely free and ready to use"
      },
      {
       "expr": "node_memory_active_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "Active - Memory currently being used by a process"
      },
      {
       "expr": "node_memory_buffer_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "Buffers - Disk cache"
      },
      {
       "expr": "node_memory_wired_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "Wired - Memory in use by the Kernel"
      },
      {
       "expr": "node_memory_free_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "Free -  Memory that has been freed but is still cached since it may be used again"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Memory Swap in/out",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_memory_swap_in_bytes_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Swap in"
      },
      {
       "expr": "irate(node_memory_swap_out_bytes_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Swap out"
      }
     ]
    },
    {
     "title": "Disk Percentage Used",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",mountpoint=\"/\"})",
       "legendFormat": "{{device}} - {{mountpoint}} "
      }
     ]
    },
    {
     "title": "Disk Space Available / Used",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes used (-) / available (+)" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\"} - node_filesystem_free_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "{{device}} - {{mountpoint}} - Used"
      },
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "{{device}} - {{mountpoint}} - Available"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Packets",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Transmit packets"
      },
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Receive packets"
      }
     ]
    },
    {
     "title": "Network Traffic Drops",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_errs_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Transmit errors"
      },
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_multicast_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Transmit multicast"
      },
      {
       "expr": "irate(node_network_receive_multicast_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_exec_context_switches_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Context switches"
      }
     ]
    },
    {
     "title": "Context Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_exec_device_interrupts_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Device Interrupts"
      },
      {
       "expr": "irate(node_exec_software_interrupts_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Software Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node:$port\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node:$port\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node:$port\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "System Calls",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_exec_system_calls_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "System calls"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Forks / sec" }
     ],
     "targets": [
      {
       "expr": "rate(node_exec_forks_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Traps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_exec_traps_total{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Traps"
      }
     ]
    },
    {
     "title": "Time Variation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_time_seconds{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Of reported time"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node:$port\",device!~'rootfs'}",
       "legendFormat": "{{device}} - {{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "Filesystem Filenodes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Filenodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"$node:$port\"}",
       "legendFormat": "{{device}} - {{mountpoint}} - Filenodes free"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Read Only" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=~\"$node:$port\",device!~'rootfs'}",
       "legendFormat": "{{device}} - {{mountpoint}} - ReadOnly"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration of a collector scrape",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_scrape_collector_duration_seconds{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Whether a collector fails",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_success{instance=~\"$node:$port\"} -1",
       "legendFormat": "{{collector}} - Scrape fail"
      },
      {
       "expr": "node_textfile_scrape_error{instance=~\"$node:$port\"}",
       "legendFormat": "opening or reading a file  - Scrape fail"
      }
     ]
    }
   ]
  }
 ]
}